# ビルドステージ
FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# ここで tidy（ソースも含めて解決できる）
RUN go mod tidy

RUN go build -o main ./cmd/

# 実行ステージ
FROM gcr.io/distroless/base-debian12

WORKDIR /

COPY --from=builder /app/main /main

ENV PORT=8080

CMD ["/main"]
