# ビルドステージ
FROM golang:1.20 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

# アプリケーションをビルド
RUN go build -o main .

# 実行ステージ（軽量イメージにする）
FROM gcr.io/distroless/base-debian11

WORKDIR /

COPY --from=builder /app/main /main

# Cloud Runが使用するデフォルトポート
ENV PORT=8080

# HTTPサーバーを起動
CMD ["/main"]
